init:
  - git config --global core.autocrlf input
build_script:
  - cmd: build.cmd
test: off
version: 0.0.1.{build}
image: .NET 5 SDK 5.0.103
install:
  - cmd: choco install dotnetcore-sdk -y
artifacts:
  - path: bin
    name: bin
  - path: dist
    name: dist
